image: node:6

stages:
#  - test
  - build
  - deploy

.build:
  stage: build
  script:
    - yarn install --frozen-lockfile
    - yarn build
  artifacts:
    paths:
      - public/

cache:
  paths:
    - node_modules/

#test:
#  stage: test
#  script:
#    - yarn install
#    - yarn test

build:pages:
  extends: .build
  variables:
    SITE_HOST: https://hkoscon.gitlab.io

build:gh-pages:
  extends: .build
  variables:
    SITE_HOST: https://hkoscon.org

pages:
  stage: deploy
  dependencies:
    - build:pages
  script:
    - rm ./public/.gitignore
  artifacts:
    paths:
      - public

deploy:gh-pages:
  stage: deploy
  dependencies:
    - build:gh-pages
  script:
    # deploy to gh-pages branch
    - rm ./public/.gitignore
    - cd public
    - ls -la
    - git init
    - git config user.name "$GITLAB_USER_NAME"
    - git config user.email "$GITLAB_USER_EMAIL"
    - git remote add origin https://$GITLAB_PAGES_USER:$GITLAB_PAGES_PASS@$(echo $CI_REPOSITORY_URL | cut -d'@' -f2)
    - git status
    - git fetch && git reset origin/gh-pages || git reset $(git rev-list --max-parents=0 HEAD)
    - git status
    - git add -A .
    - 'git commit -m "CI: Build of ${CI_COMMIT_SHA}"'
    - git push origin HEAD:gh-pages
    - rm -rf .git

